[build]
  publish = "."
  
[[redirects]]
  from = "/api/*"
  to = "https://survey-africa-backend.up.railway.app/api/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200